# Generated by Django 2.0.7 on 2018-07-14 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='runtimeMinutes',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='movie',
            name='startYear',
            field=models.IntegerField(),
        ),
    ]
