# Generated by Django 2.0.7 on 2018-07-14 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20180713_2009'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Movie',
        ),
    ]
