# Generated by Django 2.0.7 on 2018-07-14 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('movies', '0003_delete_movie'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=255)),
                ('director_name', models.CharField(max_length=255)),
                ('num_critic_for_reviews', models.CharField(max_length=255)),
                ('duration', models.IntegerField()),
                ('director_facebook_likes', models.CharField(max_length=255)),
                ('actor_3_facebook_likes', models.CharField(max_length=255)),
                ('actor_2_name', models.CharField(max_length=255)),
                ('actor_1_facebook_likes', models.IntegerField()),
                ('gross', models.CharField(max_length=255)),
                ('genres', models.CharField(max_length=255)),
                ('actor_1_name', models.CharField(max_length=255)),
                ('movie_title', models.CharField(max_length=255)),
                ('num_voted_users', models.IntegerField()),
                ('cast_total_facebook_likes', models.IntegerField()),
                ('actor_3_name', models.CharField(max_length=255)),
                ('facenumber_in_poster', models.IntegerField()),
                ('plot_keywords', models.CharField(max_length=255)),
                ('movie_imdb_link', models.CharField(max_length=255)),
                ('num_user_for_reviews', models.CharField(max_length=255)),
                ('language', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('content_rating', models.CharField(max_length=255)),
                ('budget', models.CharField(max_length=255)),
                ('title_year', models.CharField(max_length=255)),
                ('actor_2_facebook_likes', models.IntegerField()),
                ('imdb_score', models.CharField(max_length=255)),
                ('aspect_ratio', models.CharField(max_length=255)),
                ('movie_facebook_likes', models.IntegerField()),
            ],
        ),
    ]
