# Generated by Django 2.0.7 on 2018-07-16 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_userratings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userratings',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='movie', to='movies.Movie'),
        ),
    ]
