# Generated by Django 2.0.7 on 2018-07-16 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0008_auto_20180716_0300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userratings',
            name='movie',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='userratings',
            name='user',
            field=models.IntegerField(),
        ),
    ]
